### ISSUE TITLE
Ticket #1256 DevOps - backend test scripts

### ISSUE THREAD

**Issue by rayymlai** [audacyDevOps/quindar-angular#7]
This ticket will create backend (e.g. REST API) test scripts and set up and end-to-end testing for Quindar in Jenkins.

# User Story
As a DevOps engineer, I can initiate unit and backend server testing from Jenkins continuous integration server before code deployment.

# Scope
Test automation to integrate telemetry simulator with Jenkins continuous integration server. This includes:

* create grunt tasks to automate JavaScript testings
* create Mocha, Jasmine and Karma for JavaScript testing
* Add a Jenkins job to initiate the grunt task for Mocha/Jasmine/Karma test scripts 

# Tasks
* Sanity test (on-boarding task)
  - Open a Web browser to validate all REST APIs (roughly 60 APIs)  published under http://platform.audacy.space:7902/api

  - Download and install "curl" on your laptop (windows or mac)
This tool will be used to test REST API
  - Look up and study http://platform.audacy.space:7902/api 
the api doc usually provides examples and instructions how to test using "curl"

  - to test HTTP GET (read only) APIs, you can use "curl", e.g.

```
%curl -X GET http://platform.audacy.space:7902/services/v1/attitude/IBEX/10
```

  -  to test HTTP POST (write to database) APIs, you can use "curl", e.g.

```
%curl -X POST -H "Content-Type: application/json" -d  '{ xxxx: xxx, xx, xxxx }' http://platform.audacy.space:7902/services/v1/attitude
```

Reference - http://stackoverflow.com/questions/7172784/how-to-post-json-data-with-curl-from-terminal-commandline-to-test-spring-rest

* Study REST API source codes ​https://github.com/audacyDevOps/quindar-angular and ​https://github.com/audacyDevOps/quindarWidgets 
* and define (1) positive and (2) negative test cases

* check API doc (captured in annotated comments in coreAdmin.js of quindar-platform). if any api has missing or incorrect tech documentation. There should be about 80 API's.

   - add a gruntfile to replace buildapidoc.sh for consistency since we are moving to gruntfile for build automation.

Example
```

exec: {
  build_api: {
    command: 'apidoc -o api -f ".*\\.js$" -i app/scripts'
  }
}
```

* Positive test cases
  * Test expected input/output for each API function
  * Test number, string, date and email format
  * Test if each REST API (e.g. app.get, app.post) handles expected data payload, e.g. /services/v1/telemetry/1 should take in a number '1' at the end 

* Negative test cases
  * Test each input data field handles invalid cases
   * Test each REST API has valid error pages for HTTP response 3xx, 4xx, and 5xx
   * Test extreme cases for each data input field, e.g. number field > 999999999999, string field handles
   * Check for cross-domain CORS, e.g. localhost client calling API with domain audacy.space
   * Test coverage - test if each parameter in a function is all covered, e.g. function x(a,b,c) - permutate each test case for x(a,_,_), x(a,b,_), ... where _ denotes null data input.
   * Test rate limit for each REST API, e.g. REST API can be served up to 10000 requests per nodejs web server instance before the server crashes 
* Add error handling structure in existing code base. Refer to https://www.joyent.com/developers/node/design/errors for details.
* Deploy Mocha scripts (e.g. commands, shell scripts) in Jenkins. 

# Appendix - Onboarding with JavaScript testing tools
* Sample testing codes are documented in footnotes in #1210.
* Mocha ​https://codeforgeek.com/2015/07/unit-testing-nodejs-application-using-mocha/
* Jasmine ​​http://jasmine.github.io/
* Chai ​​http://chaijs.com/
* Grunt ​http://gruntjs.com/getting-started 
  * Grunt file example ​https://github.com/DataTorrent/malhar-angular-dashboard/blob/master/Gruntfile.js

* Unit test examples can be found in ​https://github.com/DataTorrent/malhar-angular-dashboard/tree/master/test

**Comment by rayymlai** [comment]
# Build #0.1.0706 Bugs found
## Automated testing
* add "status" code for ~50 REST API so that Shalini can automate testing based on return code from each REST API

## Inventory of bugs found from backend test - build #0.1.0706
* issue 1
Please find this API which is returning 500 (Internal system error encountered).

GET - /services/v1/admin/metrics/trend/attitude/:vehicleId

For Example http://platform.audacy.space:7902/services/v1/admin/metrics/trend/attitude/IBEX 

* issue 2
Please find this API where vehicleId can take any string. It should return 500. However, it is returning 200 response status.

GET /services/v1/admin/metrics/vehicle/total/:vehicleId

For Example :  /services/v1/admin/metrics/vehicle/total/abccd

* issue 3
Please find this API where vehicleId can take any string. It should return 500. However, it is returning 200 response status.

GET /services/v1/admin/metrics/vehicle/total/:vehicleId/:fromTS/:toTS

For Example :  /services/v1/admin/metrics/vehicle/total/abcd/14956200/14956200

* issue 4
Please find this API where vehicleId can take any string. It should return 500. However, it is returning 200 response status.

GET /services/v1/admin/metrics/trend/position/:vehicleId/:nLimit 

For Example :   /services/v1/admin/metrics/position/total/abcd/2

* issue 5
Please find this API where vehicleId can take any string.

GET - /services/v1/admin/metrics/position/total/:vehicleId/:fromTS/:toTS

For Example :   /services/v1/admin/metrics/position/total/ahsnjs/14256892/142567389

* issue 6
Please find this API where vehicleId can take any string.

GET - /services/v1/admin/metrics/position/total/:vehicleId

For Example :   /services/v1/admin/metrics/position/total/23244asc

**Comment by shalininegi** [comment]
# Getting started with Mocha 
Mocha is a testing library for Node.js, created to be a simple, extensible, and fast testing suite. It's used for unit and integration testing, and it's a great candidate for BDD (Behavior Driven Development).
<h1> How to setup Mocha </h1>
Node's official package manager — npm — will help us set up an empty project. Npm's init command line option will launch a wizard, which creates a package.json for our project.
```
npm init

```
To install mocha, run this command 

```
npm install mocha

```


```
{
  "name": "MochaTest",
  "version": "0.0.1",
  "dependencies": {
    "body-parser": "^1.13.2",
    "express": "^4.13.1",
    "nodemon": "^1.9.2"
  },
  "devDependencies": {
    "mocha": "^2.5.3",
    "should": "^9.0.2",
    "supertest": "^1.2.0"
  }
}

```

Our project's structure will contain a test directory that is a standard place to put the Mocha test files:

```
mkdir test

```
Next, we will install our testing framework, and an expectation library called Chai that serves as a nice replacement for Node's standard assert function.

```
npm install mocha --save
npm install chai --save
npm install chai-http --save
npm install http --save
npm install supertest --save
npm install should --save
```

Note that we are using the --save option to automatically save these dependencies in our package.json file.

During the server testing phase, we will need a way to send HTTP requests. Request is an excellent choice. Install it as follows:

```
npm install request --save

```
Finally, we will also need the Express package that defines a simple DSL (domain specific language) for routing and handling incoming HTTP requests:

```
npm install express --save
```
We will set up the test command inside the package.json file, in order to run our tests simply by executing npm test from the command line.

The following command is used to invoke the Mocha binary installed locally in the ./node_modules directory:

```
./node_modules/.bin/mocha --reporter spec

```
Here is a list of optional parameters (options) that mocha [options] command takes:

-h or --help: print help information for the Mocha command
-V or --version: print the version number that’s being used
-r or --require <name>: require a module with the name provided
-R or --reporter <name>: use a reporter with the name provided
-u or --ui <name>: use the stipulated reporting user interface (such as bdd, tdd)
-g or --grep <pattern>: run tests exclusively with a matching pattern
-i or --invert: invert the --grep match pattern
-t or --timeout <ms>: set the test case time out in milliseconds (for example, 5000)
-s or --slow <ms>: set the test threshold in milliseconds (for example, 100)
-w or --watch: watch test files for changes while hanging on the terminal
-c or --colors: enable colors
-C or --no-colors: disable colors
-G or --growl: enable Mac OS X Growl notifications
-d or --debug: enable the Node.js debugger— $ node --debug
--debug-brk: enable the Node.js debugger breaking on the first line— $ node --debug-brk
-b or --bail: exit after the first test failure
-A or --async-only: set all tests in asynchronous mode
--recursive: use tests in subfolders
--globals <names>: provide comma-delimited global names
--check-leaks: check for leaks in global variables
--interfaces: print available interfaces
--reporters: print available reporters
--compilers <ext>:<module>,...: provide compiler to use

Figure1 shows an example of nyan cat reporter with the command $ mocha analyticsTest -R nyan


<img width="741" alt="screen shot 2016-07-07 at 1 29 53 pm" src="https://cloud.githubusercontent.com/assets/14255624/16668708/f11c61e6-4446-11e6-91b9-b7d3db362b10.png"> 


<h2> Understanding Mocha Hooks </h2>
A hook is a logic, typically a function or a few statements, which is executed when the associated event happens.

Mocha has hooks that are executed in different parts of suites—before the whole suite, before each test, and so on.

In addition to before and beforeEach hooks, there are after(), and afterEach() hooks. They can be used to clean up the testing setup, such as database data.

All hooks support asynchronous modes. The same is true for tests as well. For example, the following test suite is synchronous and wait for the response to finish:

```javascript

// *** POST - REST API For Telemetry drop Orbit collection ***//
 describe("POST - REST API For Telemetry drop Orbit collection",function () {
    //#1 drop orbit collection
    it("POST /services/v1/admin/cleanup/orbit - should return 200",function(){
        server
            .post("/services/v1/admin/cleanup/orbit")
            .expect(200)
            .end(function(err,res){
                console.log(res.should.have);
                res.status.should.equal(200);
                res.body.message.should.equal("collection dropped");
                res.body.message.should.not.equal("retrieve all attitude");
                done();
            });
       });
  });

```
As soon as we add a done parameter to the test’s function, our test case waits for the HTTP request to come back.

<h3>BDD with Expect.js</h3>
Expect.js is one of the BDD languages. Its syntax allows for chaining and is richer in features than core module assert. There are two options to use expect.js:

Install as a local module
Install as a part of the chai library

For the former, simply execute the following:

$ mkdir node_modules
$ npm install expect.js

And, use var expect = require('expect.js'); inside a Node.js test file. For example, the test can be written in expect.js BDD style:

```javascript
describe("GET - REST API For Telemetry orbit",function() {
    // #1 should return 200 success 
    it("GET /services/v1/orbit", function () {
        server
            .get("/services/v1/orbit")
            .expect("Content-type", /json/)
            //CORPS
            .expect("access-control-allow-origin", '*')
            .expect("access-control-allow-headers", 'X-Requested-With')
            .expect(200) 
            .end(function (err, res) {
                console.log (res.should.have);
                // HTTP status should be 200
                res.status.should.equal(200);
                res.body.message.should.equal("retrieve all orbit data points");
                res.body.message.should.not.equal("retrieve all attitude data points");
                res.body.should.have.property("status");
                res.body.should.have.property("message");
                res.body.should.have.property("data");
                for(var dataLength=0; dataLength<res.body.data.length; dataLength++){
                    res.body.data[dataLength].should.have.property("_id");
                    res.body.data[dataLength].should.have.property("timestamp");
                    res.body.data[dataLength].should.have.property("vehicleId");
                    res.body.data[dataLength].should.have.property("trajectory");
                }
                done();
            });
       });
  });

```
To run our tests, we can run this command 
```
$mocha analyticsTest --timeout 15000

```

The results of this Mocha commands are shown below: 

<img width="539" alt="screen shot 2016-07-07 at 2 05 50 pm" src="https://cloud.githubusercontent.com/assets/14255624/16669740/f4416812-444b-11e6-876b-91891fddcf10.png">

<h4> Test Result Analysis </h4>
Here's an informal test result analysis.
   * Telemetry database
   * 4 data collections: attitude, position, vehicle, orbit

| REST API | # of Test Cases | HTTP Methods | Test Results | Time Take |
| ---: | ---: | ---:| ---:| ---:|
| Analytics | 90 | GET | Pass | 153ms|
| Helper | 05 | GET | Pass | 23ms|
| System | 06 | GET | Pass | 27ms|
| Telemetry | 125 | GET/POST | Pass | 1s|



<h5> Summary </h5>
Mocha is a nice and easy DSL that makes writing tests cases quickly. Mocha's strength comes from its modularity, and using Chai styles provide an expressive language & readable style.  

<h5> References </h5>
[Testing with Mocha.js](http://brianstoner.com/blog/testing-in-nodejs-with-mocha/?__hstc=233161921.e2ac9f4c5d03673ed13a467ce24d5fad.1467918692881.1467918692881.1467918692881.1&__hssc=233161921.1.1467918692882&__hsfp=1606732037)
[Mocha Documentation](http://mochajs.org/?__hstc=233161921.e2ac9f4c5d03673ed13a467ce24d5fad.1467918692881.1467918692881.1467918692881.1&__hssc=233161921.1.1467918692882&__hsfp=1606732037)
[Chai Documentation](http://chaijs.com/?__hstc=233161921.e2ac9f4c5d03673ed13a467ce24d5fad.1467918692881.1467918692881.1467918692881.1&__hssc=233161921.1.1467918692882&__hsfp=1606732037)

**Comment by audacyDevOps** [comment]
will set up jenkins job to run automated mocha scripts
